from snakemake.utils import min_version

min_version("7.25.0")


include: "rules/common.smk"


for step, tool in [item for item in config["reads"].items() if item[1] and not item[0].startswith("_")]:

    include: f"rules/{step}/{tool}.smk"


if config["reads"]["_generate_fastqc_for"]:

    include: "rules/fastqc.smk"


wildcard_constraints:
    **get_constraints(),


rule all:
    input:
        **get_outputs(),
    localrule: True


with open(".parameters_parsed.txt", "w") as f:
    f.write(get_all_relevant_extra_params())
