from snakemake.utils import min_version

min_version("7.25.0")


localrules:
    all,
    curl__download_kraken_db,


include: "rules/common.smk"
include: "rules/read_group.smk"


for step in config["flow"]:

    include: f"rules/{step}.smk"


if config["fastqc_reports"]:

    include: "rules/fastqc.smk"


wildcard_constraints:
    **get_constraints(),


rule all:
    input:
        **get_outputs(),
