from snakemake.utils import min_version

min_version("7.25.0")


localrules:
    all,
    curl__download_kraken_db,


include: "rules/common.smk"
include: "rules/reads.smk"
include: "rules/kraken.smk"


wildcard_constraints:
    **get_constraints(),


rule all:
    input:
        **get_outputs(),
