reads: # Specify the order and methods for each read processing step. If no method is specified, the step will not be performed.
  subsampling: null
  trimming: "cutadapt" # OPT - specify method of trimming. Allowed: "cutadapt", "null".
  decontamination: null # OPT - specify method of decontamination. Allowed: "kraken", "null".
  deduplication: null
  _generate_fastqc_for: ["trimming"] # OPT - specify which steps to generate fastqc for. Allowed: "original"."subsampling", "trimming", "decontamination", "deduplication" or empty list (default: empty list).

### HYPERPARAMETERS #############################

reads__trimming__cutadapt: # Required only if "trimming" in main "flow" element. See https://cutadapt.readthedocs.io/en/stable/guide.html#read-processing-stages
  # 1st stage - trimming
  cut_from_start_r1: null # OPT - removes a specified number of bases from the beginning of the R1 read.
  cut_from_start_r2: null # OPT - removes a specified number of bases from the beginning of the R2 read.
  cut_from_end_r1: null # OPT - removes a specified number of bases from the end of the R1 read.
  cut_from_end_r2: null # OPT - removes a specified number of bases from the end of the R2 read.
  quality_cutoff_from_5_end_r1: 20 # cutoff on 5' end of R1 read. The second step.
  quality_cutoff_from_3_end_r1: 20 # cutoff on 3' end of R1 read. The second step.
  quality_cutoff_from_5_end_r2: 20 # cutoff on 5' end of R2 read. The second step.
  quality_cutoff_from_3_end_r2: 20 # cutoff on 3' end of R2 read. The second step.
  nextseq_trimming_mode: false # Modify quality-trimming algorithm to expect two-color chemistry data (NextSeq). This masks G bases to zero quality for R1 3'. Thus, `quality_cutoff_from_3_end_r1` must be defined.

  # 2nd stage - Adapter removal
  do_adapter_removal: true
  adapter_removal:
    action: "trim" # Defines an action to perform with the found adapter.
    overlap: 3 # Minimum number of bases required to overlap with the adapter (default: 3).
    error_rate: 0.1 # Error tolerance used when searching for adapter (default: 0.1).
    adapters_anywhere_file: "test_data/adapters.fa" # Adapters fasta used for adapter trimming (no default - must be set if used).
    times: 1 # How many times to do adapter removal (default: 1).
    keep_trimmed_only: false # Discard reads with no adapters found (default: false).
    adapters_3_end_file: ""
    adapters_5_end_file: ""

  # 3rd stage - post adapter trimming
  shorten_to_length: null # OPT - both R1 and R2 are shortened to this length.
  trim_N_bases_on_ends: false # OPT - trim flanking N's on both read ends.

  # 4th stage - Filtering
  min_length_r1: null # OPT - minimum R1 read length. If R1 read is shorter, both R1 and R2 reads are discarded. The fourth step.
  min_length_r2: null # OPT - minimum R2 read length. If R2 read is shorter, both R1 and R2 reads are discarded. The fourth step.
  max_length_r1: null # OPT - maximum R1 read length. If R1 read is longer, both R1 and R2 reads are discarded. The fourth step.
  max_length_r2: null # OPT - maximum R2 read length. If R2 read is longer, both R1 and R2 reads are discarded. The fourth step.
  max_n_bases: null # OPT - Discard read if R1 or R2 has more than the specified number of N bases. The fifth step.
  max_expected_errors: null # OPT - Discard read if R1 or R2 has more expected errors than this.

### RESOURCES #############################

max_threads: 2
max_mem_mb: 6192

resources:
  reads__trimming_mem_mb: 4096
  reads__fastqc_mem_mb: 2048

threads:
  reads__trimming: 4
  reads__fastqc: 1
